### PR TITLE
Update zig-bootstrap to llvm 11.0.0-rc5

### PR DESCRIPTION
**Pull request by FireFox317**
I tested this for target `x86_64-linux-musl` and it almost works. Just the last step, cross-compiling Zig with Zig itself fails on the cmake line:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LLVM_LLVMX86UTILS_LIB
    linked by target "zigcpp" in directory /home/timonkr/zig-bootstrap/zig
```
I searched for this, but couldn't find a mention of it somewhere. Maybe someone has a clue?

Edit: Found the cause of the issue!

### CODE REVIEW

**Comment by FireFox317** [comment]
This is now blocked on ziglang/zig#6576 and ziglang/zig#6575

**Comment by FireFox317** [comment]
Now also blocked on ziglang/zig#6588. If that is merged then the `arm-linux-musleabihf` target also works :)

**Comment by FireFox317** [comment]
`x86_64-windows-gnu-baseline` build fine too, except it outputted these warnings. So probably the clang flags still have to be updated in the llvm11 branch.
```
warning: unsupported linker arg: --whole-archive
warning: unsupported linker arg: --no-whole-archive
warning: unsupported linker arg: --out-implib
warning: unsupported linker arg: zigcpp/libzig.dll.a
```

**Comment by andrewrk** [comment]
Great work, @FireFox317! I'm taking a look at the linked issues now.

**Pull request merged**
