### PR TITLE
Remove accidental bash dependency in build

### LINKED ISSUE #22: Bootstrap script fails with /bin/sh -> dash
Trying out Zig 0.6.0 (Congratulations on the release! :tada:), the bootstrap tarball fails to run by default on my Ubuntu 18.04 laptop, which apparently uses `dash` as its `/bin/sh` by default:
```
heidezomp@falafel% ./build -j1 native native
./build: 13: ./build: Bad substitution
heidezomp@falafel% ls -l /bin/sh
lrwxrwxrwx 1 root root 4 okt  2  2019 /bin/sh -> dash*
```
Changing the shebang to use `/bin/bash` works.

Not sure if this is actually a bug, but the README states this script requires a POSIX shell, which according to dash's man page, it is.

### PR DESCRIPTION
**Pull request by tiehuis**
Fixes #22.

POSIX method for uppercasing taken from here:
https://stackoverflow.com/questions/12420317/first-character-of-a-variable-in-a-shell-script-to-uppercase

### CODE REVIEW

**Comment by tiehuis** [comment]
Tested with `dash-0.5.10.2-2`.

**Comment by andrewrk** [comment]
Thanks! This is good but now we need to additionally document in the README that `cut`, `tr`, `echo` are also required system dependencies, unless those are provided by POSIX shell.

**Comment by tiehuis** [comment]
Pretty sure these are part of POSIX but let me find a source for confirmation.

**Comment by tiehuis** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cut.html
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/tr.html

These are all part of the base POSIX specification. Don't know how pedantic we want to be in regards to mentioning a POSIX shell vs. a POSIX system/environment.

**Comment by heidezomp** [comment]
I can confirm this also works with my dash 0.5.8-2.10.

**Pull request merged**
